-- MySQL Script generated by MySQL Workbench
-- Tue May 17 18:56:17 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema laboratorium
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema laboratorium
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `laboratorium` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `laboratorium` ;

-- -----------------------------------------------------
-- Table `laboratorium`.`osoba`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `laboratorium`.`osoba` (
  `idosoby` VARCHAR(45) NOT NULL,
  `nazwisko` VARCHAR(200) NULL DEFAULT NULL,
  `imie` VARCHAR(200) NULL DEFAULT NULL,
  `adres` VARCHAR(200) NULL DEFAULT NULL,
  `pesel` VARCHAR(200) NULL DEFAULT NULL,
  `mail` VARCHAR(200) NULL DEFAULT NULL,
  `telefon` VARCHAR(200) NULL DEFAULT NULL,
  `haslo` VARCHAR(200) NULL DEFAULT NULL,
  PRIMARY KEY (`idosoby`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `laboratorium`.`analityk`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `laboratorium`.`analityk` (
  `idanalityka` INT NOT NULL AUTO_INCREMENT,
  `idosoby` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idanalityka`, `idosoby`),
  INDEX `fk_analityk_osoba1_idx` (`idosoby` ASC) VISIBLE,
  CONSTRAINT `fk_analityk_osoba1`
    FOREIGN KEY (`idosoby`)
    REFERENCES `laboratorium`.`osoba` (`idosoby`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `laboratorium`.`badanie`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `laboratorium`.`badanie` (
  `idbadania` INT NOT NULL AUTO_INCREMENT,
  `nazwabadania` VARCHAR(100) NULL DEFAULT NULL,
  `cennik` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idbadania`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `laboratorium`.`pacjenci`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `laboratorium`.`pacjenci` (
  `idpacjenta` INT NOT NULL AUTO_INCREMENT,
  `idosoby` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idpacjenta`, `idosoby`),
  INDEX `fk_pacjenci_osoba1_idx` (`idosoby` ASC) VISIBLE,
  CONSTRAINT `fk_pacjenci_osoba1`
    FOREIGN KEY (`idosoby`)
    REFERENCES `laboratorium`.`osoba` (`idosoby`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci
COMMENT = '			';


-- -----------------------------------------------------
-- Table `laboratorium`.`personelrecepcji`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `laboratorium`.`personelrecepcji` (
  `idrecepcjonistki` INT NOT NULL AUTO_INCREMENT,
  `idosoby` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idrecepcjonistki`, `idosoby`),
  INDEX `fk_personelrecepcji_osoba1_idx` (`idosoby` ASC) VISIBLE,
  CONSTRAINT `fk_personelrecepcji_osoba1`
    FOREIGN KEY (`idosoby`)
    REFERENCES `laboratorium`.`osoba` (`idosoby`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `laboratorium`.`pielegniarki`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `laboratorium`.`pielegniarki` (
  `idpielegniarki` INT NOT NULL AUTO_INCREMENT,
  `idosoby` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idpielegniarki`, `idosoby`),
  INDEX `fk_pielegniarki_osoba1_idx` (`idosoby` ASC) VISIBLE,
  CONSTRAINT `fk_pielegniarki_osoba1`
    FOREIGN KEY (`idosoby`)
    REFERENCES `laboratorium`.`osoba` (`idosoby`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `laboratorium`.`wizyta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `laboratorium`.`wizyta` (
  `idpacjenta` INT NOT NULL,
  `idpielegniarki` INT NOT NULL,
  `idwizyty` INT NOT NULL AUTO_INCREMENT,
  `datawizyty` DATETIME NULL DEFAULT NULL,
  `idbadania` INT NOT NULL,
  PRIMARY KEY (`idwizyty`),
  INDEX `idpielegniarki` (`idpielegniarki` ASC) VISIBLE,
  INDEX `idpacjenta` (`idpacjenta` ASC) VISIBLE,
  INDEX `idwizyty_idx` (`idwizyty` ASC) INVISIBLE,
  INDEX `idwizyty` (`idwizyty` ASC) VISIBLE,
  INDEX `idbadania` (`idbadania` ASC) VISIBLE,
  CONSTRAINT `idpacjenta`
    FOREIGN KEY (`idpacjenta`)
    REFERENCES `laboratorium`.`pacjenci` (`idpacjenta`),
  CONSTRAINT `idpielegniarki`
    FOREIGN KEY (`idpielegniarki`)
    REFERENCES `laboratorium`.`pielegniarki` (`idpielegniarki`),
  CONSTRAINT `idbadania`
    FOREIGN KEY (`idbadania`)
    REFERENCES `laboratorium`.`badanie` (`idbadania`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `laboratorium`.`recepcja`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `laboratorium`.`recepcja` (
  `idwizyty` INT NOT NULL,
  `idrecepcjonistki` INT NOT NULL,
  PRIMARY KEY (`idrecepcjonistki`),
  INDEX `idrecepcjonistki_idx` (`idrecepcjonistki` ASC) VISIBLE,
  INDEX `idwizyty1` (`idwizyty` ASC) VISIBLE,
  CONSTRAINT `idrecepcjonistki`
    FOREIGN KEY (`idrecepcjonistki`)
    REFERENCES `laboratorium`.`personelrecepcji` (`idrecepcjonistki`),
  CONSTRAINT `idwizyty_a`
    FOREIGN KEY (`idwizyty`)
    REFERENCES `laboratorium`.`wizyta` (`idwizyty`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `laboratorium`.`wykonaniabadania`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `laboratorium`.`wykonaniabadania` (
  `idwizyty` INT NOT NULL,
  `idanalityka` INT NOT NULL,
  `idbadania` INT NOT NULL,
  `data` DATETIME NULL DEFAULT NULL,
  `wyniki` VARCHAR(100) NULL DEFAULT NULL,
  `cenaaktualna` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`idbadania`),
  INDEX `idanalityka_idx` (`idanalityka` ASC) VISIBLE,
  INDEX `idbadania_idx` (`idbadania` ASC) VISIBLE,
  INDEX `idwizyty_idx` (`idwizyty` ASC) INVISIBLE,
  CONSTRAINT `idanalityka`
    FOREIGN KEY (`idanalityka`)
    REFERENCES `laboratorium`.`analityk` (`idanalityka`),
  CONSTRAINT `idbadania`
    FOREIGN KEY (`idbadania`)
    REFERENCES `laboratorium`.`badanie` (`idbadania`),
  CONSTRAINT `idwizyty_b`
    FOREIGN KEY (`idwizyty`)
    REFERENCES `laboratorium`.`wizyta` (`idwizyty`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
